#!/bin/bash
#Envoie toutes les décisions et alerts crowdsec par mail.
#Variables
DATA="/home/freax/crowdsec"
NAME=$(date +%Y%m%d-%H%M%S)
#FIN
mkdir ${DATA}
cscli alerts list > ${DATA}/alerts.txt
cscli decisions list > ${DATA}/decisions.txt
echo "Crowdsec : ${NAME} Alerts et Décision du jours"| mail -s "CROWDSEC" backup.freax@gmail.com -A ${DATA}/alerts.txt -A ${DATA}/decisions.txt
rm -r ${DATA}
