#!/bin/bash
#Met a jour automatiquement, plus envoie des logs par mail.
#Variables
UPDATE_NOM=$(date +%Y%m%d-%H%M%S)
LOG="var/log/apt"
#FIN
apt update
apt list --upgradable > ${LOG}/upgradable
apt upgrade -y
apt auto-remove -y
echo "Update : ${UPDATE_NOM}-fini. Tous les paquets sont à jours"| mail -s "UPDATE AUTO" mail@gmail.com -A ${LOG}/term.log -A ${LOG}/history.log -A ${LOG}/upgradable
rm ${LOG}/*
